### ISSUE TITLE
What is this error? after upgrade xcode to 8.

### ISSUE THREAD

**Issue by kevinblade** [jhen0409/remote-redux-devtools-on-debugger#16]
Hi!.

I encountered following error using remote-redux-devtools-on-debugger@0.5.1.
I can't recover from #15 issue. So, I have used 0.5.1
But after xcode upgrade I have received following error.
How can I fix it. Help me please.

1474537500436 - Origin: Worker (PID 12396)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/Users/user1/Documents/Works/bia_project/cood_bia_mobile/node_modules/remotedev-server/node_modules/socketcluster-server/scsocket.js:177:17)
    at WebSocket.<anonymous> (/Users/user1/Documents/Works/bia_project/cood_bia_mobile/node_modules/remotedev-server/node_modules/socketcluster-server/scsocket.js:54:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/Users/user1/Documents/Works/bia_project/cood_bia_mobile/node_modules/remotedev-server/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by zalmoxisus** [comment]
Unfortunately there aren't any details here. Maybe you can find something in that line causing the error (`/Users/user1/Documents/Works/bia_project/cood_bia_mobile/node_modules/remotedev-server/node_modules/socketcluster-server/scsocket.js:54:10`). It seems that you're using a different version than https://github.com/SocketCluster/socketcluster-server/blob/master/scsocket.js

**Comment by mmmurf** [comment]
Any new info on this? I believe it's happening to me too.

**Comment by brunolemos** [comment]
This started happening to me today. The remote dev tools is no longer working.

**Comment by brunolemos** [comment]
Well I changed the port, upgraded some packages (firebase, ...) and it's working again ¯\_(ツ)_/¯

**Comment by brunolemos** [comment]
Actually it happens randomly. Maybe it has something to do with other sockets on my project (firebase, ...).

**Comment by zalmoxisus** [comment]
@brunolemos try to [start a local server](https://github.com/zalmoxisus/remote-redux-devtools#communicate-via-local-server) instead. By default it is connecting to `remotedev.io`.

**Comment by brunolemos** [comment]
@zalmoxisus Im using local server, its working fine now, nevermind. I really believe it has something with firebase, because I was not using it before...

**Comment by timzaak** [comment]
I have met the same problem, but that is because the port is error.
