### ISSUE TITLE
_server is not defined

### ISSUE THREAD

**Issue by mint3000** [jhen0409/remote-redux-devtools-on-debugger#17]
Hi, I'm getting this error after running `npm run postinstall` then `react-native run-ios`:

```
/Users/ryanh/REPOS/cm-gallery-starter-kit/node_modules/react-native/local-cli/server/server.js:6
  _server(argv, config, resolve, reject);
  ^

ReferenceError: _server is not defined
    at EventEmitter.<anonymous> (/Users/ryanh/REPOS/cm-gallery-starter-kit/node_modules/react-native/local-cli/server/server.js:6:11)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at EventEmitter.emit (/Users/ryanh/REPOS/cm-gallery-starter-kit/node_modules/sc-domain/index.js:12:31)
    at EventEmitter.SocketCluster._logDeploymentDetails (/Users/ryanh/REPOS/cm-gallery-starter-kit/node_modules/socketcluster/index.js:600:8)
    at EventEmitter.SocketCluster._workerClusterReadyHandler (/Users/ryanh/REPOS/cm-gallery-starter-kit/node_modules/socketcluster/index.js:475:10)
    at ChildProcess.workerHandler (/Users/ryanh/REPOS/cm-gallery-starter-kit/node_modules/socketcluster/index.js:576:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at ChildProcess.EventEmitter.emit (/Users/ryanh/REPOS/cm-gallery-starter-kit/node_modules/sc-domain/index.js:12:31)
```
Here's my postinstall:

```
"scripts": {
    "postinstall": "remotedev-debugger --hostname localhost --port 5678 --injectserver"
}
```

Any help would be appreciated :)

**Comment by mint3000** [comment]
Turns out I had to update to the latest version, closing this issue.
